#ifndef BRUTCODE_H
#define BRUTCODE_H

char header[] = "%struct.CarElt = type {\n"
"	i32,\n"
"	%struct.tInitCar,\n"
"	%struct.tPublicCar,\n"
"	%struct.tCarRaceInfo,\n"
"	%struct.tPrivCar,\n"
"	%struct.tCarCtrl,\n"
"	%struct.tCarPitCmd,\n"
"	%struct.RobotItf*,\n"
"	%struct.CarElt*\n"
"}\n"
"\n"
"%struct.tInitCar = type {\n"
"	[32 x i8],\n"
"	[32 x i8],\n"
"	[32 x i8],\n"
"	[32 x i8],\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	[3 x float],\n"
"	%struct.t3Dd,\n"
"	%struct.t3Dd,\n"
"	%struct.t3Dd,\n"
"	float,\n"
"	float,\n"
"	%struct.t3Dd,\n"
"	[4 x %struct.tWheelSpec],\n"
"	%struct.tVisualAttributes\n"
"}\n"
"\n"
"%struct.t3Dd = type {\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.tWheelSpec = type {\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.tVisualAttributes = type {\n"
"	i32,\n"
"	[2 x %struct.t3Dd],\n"
"	float\n"
"}\n"
"\n"
"%struct.tPublicCar = type {\n"
"	%struct.tDynPt,\n"
"	%struct.tDynPt,\n"
"	[4 x [4 x float]],\n"
"	%struct.tTrkLocPos,\n"
"	i32,\n"
"	[4 x %struct.tPosd]\n"
"}\n"
"\n"
"%struct.tDynPt = type {\n"
"	%struct.tPosd,\n"
"	%struct.tPosd,\n"
"	%struct.tPosd\n"
"}\n"
"\n"
"%struct.tPosd = type {\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.tTrkLocPos = type {\n"
"	%struct.trackSeg*,\n"
"	i32,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.trackSeg = type {\n"
"	i8*,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	%struct.t3Dd,\n"
"	[4 x %struct.t3Dd],\n"
"	[7 x float],\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	%struct.t3Dd,\n"
"	i32,\n"
"	float,\n"
"	i32,\n"
"	float,\n"
"	%struct.SegExt*,\n"
"	%struct.trackSurface*,\n"
"	[2 x %struct.trackBarrier*],\n"
"	%struct.RoadCam*,\n"
"	%struct.trackSeg*,\n"
"	%struct.trackSeg*,\n"
"	%union.anon.0\n"
"}\n"
"\n"
"%struct.SegExt = type {\n"
"	i32,\n"
"	i32*\n"
"}\n"
"\n"
"%struct.trackSurface = type {\n"
"	%struct.trackSurface*,\n"
"	i8*,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.trackBarrier = type {\n"
"	i32,\n"
"	float,\n"
"	float,\n"
"	%struct.trackSurface*,\n"
"	%class.v2t\n"
"}\n"
"\n"
"%class.v2t = type {\n"
"	%union.anon\n"
"}\n"
"\n"
"%union.anon = type {\n"
"	%struct.anon\n"
"}\n"
"\n"
"%struct.anon = type {\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.RoadCam = type {\n"
"	i8*,\n"
"	%struct.t3Dd,\n"
"	%struct.RoadCam*\n"
"}\n"
"\n"
"%union.anon.0 = type {\n"
"	%struct.anon.1\n"
"}\n"
"\n"
"%struct.anon.1 = type {\n"
"	%struct.trackSeg*,\n"
"	%struct.trackSeg*\n"
"}\n"
"\n"
"%struct.tCarRaceInfo = type {\n"
"	double,\n"
"	i8,\n"
"	double,\n"
"	double,\n"
"	double,\n"
"	double,\n"
"	float,\n"
"	float,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	double,\n"
"	i32,\n"
"	double,\n"
"	double,\n"
"	float,\n"
"	float,\n"
"	double,\n"
"	%struct.TrackOwnPit*,\n"
"	i32,\n"
"	%struct.CarPenaltyHead\n"
"}\n"
"\n"
"%struct.TrackOwnPit = type {\n"
"	%struct.tTrkLocPos,\n"
"	i32,\n"
"	float,\n"
"	float,\n"
"	i32,\n"
"	[4 x %struct.CarElt*]\n"
"}\n"
"\n"
"%struct.CarPenaltyHead = type {\n"
"	%struct.CarPenalty*,\n"
"	%struct.CarPenalty**\n"
"}\n"
"\n"
"%struct.CarPenalty = type {\n"
"	i32,\n"
"	i32,\n"
"	%struct.anon.2\n"
"}\n"
"\n"
"%struct.anon.2 = type {\n"
"	%struct.CarPenalty*,\n"
"	%struct.CarPenalty**\n"
"}\n"
"\n"
"%struct.tPrivCar = type {\n"
"	i8*,\n"
"	i8*,\n"
"	i32,\n"
"	[32 x i8],\n"
"	[4 x %struct.tWheelState],\n"
"	[4 x %struct.tPosd],\n"
"	i32,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	[10 x float],\n"
"	i32,\n"
"	i32,\n"
"	[4 x float],\n"
"	[4 x float],\n"
"	i32,\n"
"	i32,\n"
"	float,\n"
"	%struct.t3Dd,\n"
"	%struct.t3Dd,\n"
"	i32,\n"
"	i32,\n"
"	%struct.tCollisionState_\n"
"}\n"
"\n"
"%struct.tWheelState = type {\n"
"	%struct.tPosd,\n"
"	float,\n"
"	float,\n"
"	i32,\n"
"	%struct.trackSeg*,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.tCollisionState_ = type {\n"
"	i32,\n"
"	[3 x float],\n"
"	[3 x float]\n"
"}\n"
"\n"
"%struct.tCarCtrl = type {\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	i32,\n"
"	i32,\n"
"	[4 x [32 x i8]],\n"
"	[4 x float],\n"
"	i32\n"
"}\n"
"\n"
"%struct.tCarPitCmd = type {\n"
"	float,\n"
"	i32,\n"
"	i32,\n"
"	%struct.tCarPitSetup\n"
"}\n"
"\n"
"%struct.tCarPitSetup = type {\n"
"	%struct.tCarPitSetupValue,\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	%struct.tCarPitSetupValue,\n"
"	%struct.tCarPitSetupValue,\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[4 x %struct.tCarPitSetupValue],\n"
"	[2 x %struct.tCarPitSetupValue],\n"
"	[2 x %struct.tCarPitSetupValue],\n"
"	[2 x %struct.tCarPitSetupValue],\n"
"	[2 x %struct.tCarPitSetupValue],\n"
"	[2 x %struct.tCarPitSetupValue],\n"
"	[8 x %struct.tCarPitSetupValue],\n"
"	[2 x %struct.tCarPitSetupValue],\n"
"	[3 x %struct.tCarPitSetupValue],\n"
"	[3 x %struct.tCarPitSetupValue],\n"
"	[3 x %struct.tCarPitSetupValue],\n"
"	[3 x %struct.tCarPitSetupValue],\n"
"	[3 x %struct.tCarPitSetupValue],\n"
"	[3 x %struct.tCarPitSetupValue],\n"
"	[3 x i32]\n"
"}\n"
"\n"
"%struct.tCarPitSetupValue = type {\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.RobotItf = type {\n"
"	void (i32, %struct.tTrack*, i8*, i8**, %struct.Situation*)*,\n"
"	 {}*,\n"
"	 {}*,\n"
"	 {}*,\n"
"	 i32 (i32, %struct.CarElt*, %struct.Situation*)*,\n"
"	 void (i32)*,\n"
"	 i32\n"
"}\n"
"\n"
"%struct.tTrack = type {\n"
"	i8*,\n"
"	i8*,\n"
"	i8*,\n"
"	i8*,\n"
"	i8*,\n"
"	i8*,\n"
"	i32,\n"
"	i32,\n"
"	float,\n"
"	float,\n"
"	%struct.tTrackPitInfo,\n"
"	%struct.trackSeg*,\n"
"	%struct.trackSurface*,\n"
"	%struct.t3Dd,\n"
"	%struct.t3Dd,\n"
"	%struct.tTrackGraphicInfo\n"
"}\n"
"\n"
"%struct.tTrackPitInfo = type {\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	%struct.trackSeg*,\n"
"	%struct.trackSeg*,\n"
"	%struct.trackSeg*,\n"
"	%struct.trackSeg*,\n"
"	%struct.TrackOwnPit*,\n"
"	i32,\n"
"	i32\n"
"}\n"
"\n"
"%struct.tTrackGraphicInfo = type {\n"
"	i8*,\n"
"	i8*,\n"
"	i32,\n"
"	[3 x float],\n"
"	i32,\n"
"	i8**,\n"
"	%struct.tTurnMarksInfo\n"
"}\n"
"\n"
"%struct.tTurnMarksInfo = type {\n"
"	float,\n"
"	float,\n"
"	float,\n"
"	float\n"
"}\n"
"\n"
"%struct.Situation = type {\n"
"	%struct.tRaceAdmInfo,\n"
"	double,\n"
"	double,\n"
"	i32,\n"
"	%struct.CarElt**\n"
"}\n"
"\n"
"%struct.tRaceAdmInfo = type {\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	i32,\n"
"	i64\n"
  "}\n";

char end[] = "declare float @norm_pi_pi(float %a)\n"
"declare float @get_track_angle(%struct.tTrkLocPos*)\n"
"declare float @get_pos_to_right(%struct.tTrkLocPos*)\n"
"declare float @get_pos_to_middle(%struct.tTrkLocPos*)\n"
"declare float @get_pos_to_left(%struct.tTrkLocPos*)\n"
"declare float @get_pos_to_start(%struct.tTrkLocPos*)\n"
"declare float @get_track_seg_length(%struct.trackSeg*)\n"
"declare float @get_track_seg_width(%struct.trackSeg*)\n"
"declare float @get_track_seg_start_width(%struct.trackSeg*)\n"
"declare float @get_track_seg_end_width(%struct.trackSeg*)\n"
"declare float @get_track_seg_radius(%struct.trackSeg*)\n"
"declare float @get_track_seg_right_radius(%struct.trackSeg*)\n"
"declare float @get_track_seg_left_radius(%struct.trackSeg*)\n"
"declare float @get_track_seg_arc(%struct.trackSeg*)\n"
"declare %struct.trackSeg* @get_track_seg_next(%struct.trackSeg*)\n"
  "declare float @get_car_yaw(%struct.CarElt*)\n";


#endif
